language: python
cache: pip
python:
- '3.5'
- '3.6'
install:
- pip install .
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: garylai1990
  on:
    python: 3.5
    branch: master
  password:
    secure: CX4ik1LGlYvxtYsVLl/6fbCBEaszcuCs2+CVAo2tyCUyV7oMhh6UIBuFxaW891yF/kzVbnfa6+OfjmV2gYwAmehDcraFml/2FKFRyfUBOgJsel766WNl+b4oUZttzJqEZHASNAsA/WPBYqfD+dQQJ4U9FmMZm94jvsfUDD/uVAZeTZPc+EUJjWCgqGD5NHmuZeMtgx+bZUVo+Uuv9o4d1s6A5Mueq4xKU0kLJ8B+InmY1Fgrp0mbBmByss7qdp/jsEwiqDG213QrqRSGrTmKQeLRjxc4kg+4gu17sOTn2HgPdPPD6iTv+ul/8XXXBUfGELGyeCo461itZqrd4Oclrtl7e3doWJaiMBjOi1lcuxa3sTKYg440dQJCrM/ZroX0gQKxbiwZJryVYogm8UiyAfzL/2nsMsMM3PjQjvYaBC2632hR/ljK3Y3mpkBq+L557yrKfAIiA9u/hts8iIT113TfP9JS5rNlEmKun/Zteznzkj3zsDl7kOTrIKP1xqcdKfBaHvq32aiGK2su9S+Bcp9RCHzA2Lj2reCqjhMfrKGP7KeFKdZR753aK+ATigOUYa//yBNcLbT940MAdksgpsnHTR126nMTo2cKnn+nlbbVtBW+iKslDSTMvaEvsDxexte4eEA3z/Rb8iO6vlVwNHmorbKqnBVaPbYRElGu9lE=
script:
- pytest
notifications:
  email: false
